/*
 * Copyright (c) 2024-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of TOTP.ts <https://github.com/OpenChargingCloud/TOTP.ts>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Runs this implementation against the canonical conformance test vectors in
// test/vectors/ - vendored, byte for byte, from
// https://github.com/OpenChargingCloud/TOTPConformanceTests (TestVectors/),
// where they are generated by an independent reference implementation and
// also run against the C# TOTPGenerator in Vanaheimr Hermod. Regenerate them
// THERE (tools/generate-test-vectors.py mirrors them into this folder); the
// conformance suite fails when this copy drifts.
//
// Every vector is run through BOTH call styles - positional arguments and the
// options object - which pins their equivalence across the whole vector set.

import { readFileSync } from "node:fs";

import { describe, expect, it } from "vitest";

import { generateTOTPs, type TOTPHashAlgorithm } from "../src/index.js";


const IMPLEMENTATION_NAME = "totp.ts";

/** The optional capabilities this implementation provides ("requires" lists). */
const CAPABILITIES: ReadonlySet<string> = new Set([]);

/** Every capability name that exists in the vector format at all: a vector
 *  requiring anything else means the files are newer than this suite - fail,
 *  never skip silently. */
const KNOWN_CAPABILITIES: ReadonlySet<string> = new Set([
    "tlsChannelBinding",
    "httpAuthentication"
]);


interface VectorInput {
    sharedSecret:            string;
    unixTimestampMillis:     number;
    validityTimeSeconds?:    number;
    totpLength?:             number;
    alphabet?:               string;
    hashAlgorithm?:          string;
    tlsExporterMaterialHex?: string;
}

interface GenerationVector {
    id:        string;
    input:     VectorInput;
    expected: {
        previous:              string;
        current:               string;
        next:                  string;
        remainingTimeSeconds:  number;
    };
    requires?: string[];
}

interface InvalidInputVector {
    id:                string;
    input:             VectorInput;
    expectedError:     string;
    knownDeviations?:  string[];
    notApplicable?:    string[];
}


function load<T>(fileName: string): { requires?: string[]; vectors: T[] } {
    return JSON.parse(
        readFileSync(new URL(`./vectors/${fileName}`, import.meta.url), "utf-8")
    ) as { requires?: string[]; vectors: T[] };
}

const generationVectors    = load<GenerationVector>  ("totp-test-vectors.json").vectors;
const invalidInputVectors  = load<InvalidInputVector>("totp-invalid-inputs.json").vectors;

// The HTTP authentication vectors (spec/totp-http-authentication.md) are
// capability-gated as a whole file: this library implements no HTTP binding,
// so only the gate is checked and the file is skipped DECLARATIVELY below.
const httpAuthFileRequires = load<unknown>          ("totp-http-auth-vectors.json").requires ?? [];


function positional(input: VectorInput) {
    return generateTOTPs(
        input.sharedSecret,
        input.validityTimeSeconds ?? null,
        input.totpLength          ?? null,
        input.alphabet            ?? null,
        input.unixTimestampMillis,
       (input.hashAlgorithm       ?? null) as TOTPHashAlgorithm | null
    );
}

function viaOptions(input: VectorInput) {
    return generateTOTPs({
        sharedSecret:   input.sharedSecret,
        validityTime:   input.validityTimeSeconds ?? null,
        totpLength:     input.totpLength          ?? null,
        alphabet:       input.alphabet            ?? null,
        timestamp:      input.unixTimestampMillis,
        hashAlgorithm: (input.hashAlgorithm       ?? null) as TOTPHashAlgorithm | null
    });
}


describe("Vector files", () => {

    it("are loaded", () => {
        expect(generationVectors.length).toBeGreaterThanOrEqual(30);
        expect(invalidInputVectors.length).toBeGreaterThanOrEqual(15);
    });

    it("require only capabilities this suite knows about", () => {
        const unknown = [ ...generationVectors.flatMap(vector => vector.requires ?? []),
                          ...httpAuthFileRequires ]
            .filter(capability => !KNOWN_CAPABILITIES.has(capability));
        expect(unknown).toEqual([]);
    });

    const missingHttp = httpAuthFileRequires.filter(capability => !CAPABILITIES.has(capability));

    if (missingHttp.length > 0)
        it.skip(`totp-http-auth-vectors.json (requires: ${missingHttp.join(", ")})`, () => {});

});


describe("Generation vectors", () => {

    for (const vector of generationVectors) {

        const missing = (vector.requires ?? []).filter(capability => !CAPABILITIES.has(capability));

        if (missing.length > 0) {
            it.skip(`${vector.id} (requires: ${missing.join(", ")})`, () => {});
            continue;
        }

        it(vector.id, () => {
            const expected = {
                previous:       vector.expected.previous,
                current:        vector.expected.current,
                next:           vector.expected.next,
                remainingTime:  vector.expected.remainingTimeSeconds
            };
            expect(positional(vector.input)).toEqual(expected);
            expect(viaOptions(vector.input)).toEqual(expected);
        });

    }

});


describe("Invalid input vectors", () => {

    for (const vector of invalidInputVectors) {

        if (vector.notApplicable?.includes(IMPLEMENTATION_NAME)) {
            it.skip(`${vector.id} (not representable in this API)`, () => {});
            continue;
        }

        if (vector.knownDeviations?.includes(IMPLEMENTATION_NAME)) {
            it.skip(`${vector.id} (documented deviation, see the conformance repository)`, () => {});
            continue;
        }

        it(vector.id, () => {
            expect(() => positional(vector.input)).toThrow(vector.expectedError);
            expect(() => viaOptions(vector.input)).toThrow(vector.expectedError);
        });

    }

});
